### ISSUE TITLE
All globals variables. It should be checked that their initial value is correct.

### ISSUE THREAD

**Issue by Gh0stBlade** [TOMB5/TOMB5#12]
- [x] 3D_GEN.C
- [x] 3D_OBJ.C
- [x] BOX.C
- [x] CAMERA.C
- [x] CD.C
- [x] COLLIDE.C
- [x] CONTROL.C
- [x] DEBRIS.C
- [x] DELSTUFF.C
- [x] DOOR.C
- [x] DRAW.C
- [x] DRAWPHAS.C
- [x] DRAWSPKS.C
- [x] EFFECT2.C
- [x] EFFECTS.C
- [x] FILE.C
- [x] FLMTORCH.C
- [x] GAMEFLOW.C
- [ ] GPU.C - db, RoomTextInfo, GadwOrderingTables_V2, GadwOrderingTables, GadwPolygonBuffers
- [x] HAIR.C
- [x] HEALTH.C
- [x] ITEMS.C
- [x] LOAD_LEV.C
- [x] LOADSAVE.C
- [x] LOT.C

**Comment by zdimension** [comment]
- [ ] MALLOC.C
- [ ] MISSILE.C
- [ ] NEWINV2.C
- [ ] OBJECTS.C
- [ ] OBJLIGHT.C
- [ ] PEOPLE.C
- [ ] PICKUP.C
- [ ] SAVEGAME.C
- [ ] SOUND.C
- [ ] SPHERE.C
- [ ] SPOTCAM.C
- [ ] SWITCH.C
- [ ] TEXT.C
- [ ] TOMB4FX.C
- [ ] TRAPS.C

**Comment by Gh0stBlade** [comment]
I'd like to make you aware that default values so far are based purely off the Internal Beta PSX version. Retail PSX version and PC have not been checked.
