### ISSUE TITLE
Contributing.md missing steps to get started

### ISSUE THREAD

**Issue by duncanspumpkin** [TOMB5/TOMB5#156]
**Describe the bug**
I was trying to follow the getting started steps and I think it is missing a step about installing glew-2.1.0 into the EXTERNAL folder.

**To Reproduce**
1. Follow Contributing.md through step 1 into step 2
2. Realise that CMake cannot find glew-2.1.0. Causing no project files to be created

**Expected behavior**
There should be an additional requirement in step 1 Dependencies for glew-2.1.0.
There should be an additional bullet point in step 2 to install glew-2.1.0 into the EXTERNAL folder.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by zdimension** [comment]
Indeed. GLEW has only been required for a few weeks, we didn't find the time to add it to the file. I'll add it asap.

**Comment by Gh0stBlade** [comment]
Closing this since the build instructions have been updated.
