### ISSUE TITLE
Add unimplemented warnings when needed

### ISSUE THREAD

**Issue by zdimension** [TOMB5/TOMB5#180]
A lot of unimplented functions have been left empty, but they should contain either the `UNIMPLEMENTED()` (shared) or the `Unimpl()` (PC) macro to indicate that they are not implemented.

**Comment by Gh0stBlade** [comment]
Most of the code already does this. Some exceptions were code i was working on and suddenly moved to something else but it was still committed.

Why rename pc macro to unimpl. Unimplemented was enough and should stretch across all platforms seamlessly.

**Comment by zdimension** [comment]
Actually it's the opposite, the PC macro was there before the GAME one and it was always called UNIMPL(). When it was created, GAME still used S_Warn(...) manually everywhere, the longer version was created afterwards and I didn't bother replacing everything in PC since UNIMPL is shorter
