### ISSUE TITLE
[PSXPC_N] textures messing up underwater

### ISSUE THREAD

**Issue by Wuups** [TOMB5/TOMB5#232]
Textures get messed up when the camera goes underwater.
Here is a video showcasing the issue: https://youtu.be/LbcWpN69hpw

I assume something is trashing the texture memory. 
Some textures spotted are textures from the Ireland levels, as shown in this screenshot:
![image](https://user-images.githubusercontent.com/38836940/75222015-d3cf1280-5768-11ea-8e13-ca8f847bd8cf.png)

Tested on PSXPC_N, probably happens in other versions. I haven't tested.

**Comment by Gh0stBlade** [comment]
![image](https://user-images.githubusercontent.com/6951235/77766474-9abfe180-7037-11ea-9cd7-3a3736f0b724.png)

Fixed in latest build.
