### ISSUE TITLE
[PSXPC_N] "out of texture space error" crash

### ISSUE THREAD

**Issue by Wuups** [TOMB5/TOMB5#235]
Reproduce as in the video:
https://youtu.be/t3K3q6SWFQU

Camera has to be on the slope facing Lara for the crash to happen.
![image](https://user-images.githubusercontent.com/38836940/75273342-4f12e180-57c6-11ea-9e12-1e4004902820.png)

**Comment by Gh0stBlade** [comment]
Looks to be caused by a temporary assertion i put in place to debug an existing error. Should be resolved soon.

**Comment by Gh0stBlade** [comment]
Can you try latest code and see if this is fixed? Looks like it could be a Lara drawing issue.

**Comment by XProger** [comment]
should be fixed

**Comment by Gh0stBlade** [comment]
I already fixed this by room rendering function split.
