### ISSUE TITLE
Low ceilings issue

### ISSUE THREAD

**Issue by Trxyebeep** [TOMB5/TOMB5#237]
hitting a ceiling causes Lara's standing jumps to bug out:
https://youtu.be/Tnx7oiJMY6Y

repro steps: just take a standing jump and make Lara's head hit any ceiling.

**Comment by Gh0stBlade** [comment]
Related to Lara fall speed (?)

**Comment by Gh0stBlade** [comment]
Fixed in: https://github.com/TOMB5/TOMB5/commit/d8805bdb8524cf180a64e5c08cdc58732e92a8b8
