### ISSUE TITLE
[Specific-PSXPC_N] Infinite Loop in Colosseum

### ISSUE THREAD

**Issue by ProjectRevoTPP** [TOMB5/TOMB5#270]
When running in the following room in The Colosseum:

![image](https://user-images.githubusercontent.com/11638236/84544727-d9c31200-accb-11ea-8c53-00e2f0ad9127.png)

the game experiences an infinite loop.

In Arch Linux running gdb and quitting out of the executable, I do get this:

```
[PlaySample] - Unimplemented!
[LaraBaddieCollision] - Unimplemented!
[TestLaraVault] - Unimplemented!
[LaraGun] - Unimplemented!
^Z
Program received signal SIGTSTP, Stopped (user).
GetHeight (floor=0x56756cf0 <malloc_buffer+504080>, x=70434, y=3702, z=51353) at /home/x5core/TOMB5/SPEC_PSXPC_N/GETSTUFF.C:750
750                     value = *fd++;
(gdb) 
```

How to reproduce:
1. Load game
2. Select The Colosseum
3. Run towards the room in the screenshot, however run a little left then loop back around to the right to turn around. It should hang before the turn finishes.

**Comment by Gh0stBlade** [comment]
Solved by: https://github.com/TOMB5/TOMB5/commit/9d39ee88fe6387752e33866f0b6eb10390646e46
