### ISSUE TITLE
Methods must be re-ordered same as the original code.

### ISSUE THREAD

**Issue by Gh0stBlade** [TOMB5/TOMB5#51]
Currently some methods are incorrectly ordered, would prefer them to be in the same order as seen in psx symbol output.

**Comment by zdimension** [comment]
are we sure that the order in the psx symbol output is the real order in the code? I mean maybe the compiler reorders them etc

**Comment by Gh0stBlade** [comment]
It's likely, yes. Line numbers are key here. Best way to double check is comparing current PSX build symbols and running it through symdump.

I doubt the compiler re-orders anything.

**Comment by Gh0stBlade** [comment]
I have been slowly doing this to the best of my ability, all C functions seem fine for now.
